# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Order Placed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('replaced', 'Replaced')], default='pending', max_length=30)),
                ('customer_name', models.CharField(default='Customer', max_length=100)),
                ('customer_phone', models.CharField(default='9876543210', max_length=20)),
                ('shipping_address', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admin_commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seller_net_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_partner_earning', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI / QR Code'), ('card', 'Credit/Debit Card'), ('netbanking', 'Net Banking'), ('wallet', 'E-Wallet')], default='cod', max_length=30)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('delivery_otp', models.CharField(default='4921', max_length=6)),
                ('customer_signature', models.TextField(blank=True, default='')),
                ('proof_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('tracking_id', models.CharField(blank=True, default='', max_length=50)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
