# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=150)),
                ('store_slug', models.SlugField(unique=True)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('banner_url', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('business_address', models.TextField()),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, default='State Bank of India', max_length=100)),
                ('account_number', models.CharField(blank=True, default='987654321012', max_length=50)),
                ('ifsc_code', models.CharField(blank=True, default='SBIN0001234', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='store@upi', max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
