# Generated by Django 6.1.1 on 2026-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_sellerregistrationapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistrationapplication',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sellerregistrationapplication',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
