# Generated by Django 6.1.1 on 2026-09-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_sellerregistrationapplication_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20),
        ),
    ]
