# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Motorcycle / Bike'), ('scooter', 'Electric Scooter'), ('van', 'Delivery Van')], default='bike', max_length=50)),
                ('vehicle_number', models.CharField(max_length=30)),
                ('driving_license_no', models.CharField(max_length=50)),
                ('is_online', models.BooleanField(default=True)),
                ('current_lat', models.FloatField(default=28.6139)),
                ('current_lng', models.FloatField(default=77.209)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('bank_name', models.CharField(blank=True, default='HDFC Bank', max_length=100)),
                ('account_number', models.CharField(blank=True, default='50100234567890', max_length=50)),
                ('upi_id', models.CharField(blank=True, default='rider@okaxis', max_length=50)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
