# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('return', 'Return & Refund'), ('replace', 'Replacement')], default='return', max_length=20)),
                ('reason', models.CharField(choices=[('defective', 'Defective / Not Working'), ('damaged', 'Damaged in Transit'), ('wrong_item', 'Received Wrong Item'), ('not_as_described', 'Product Not as Described'), ('size_issue', 'Size / Fit Issue'), ('other', 'Other Reason')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Seller Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_picked_up', 'Item Picked Up'), ('refund_processed', 'Refund Completed'), ('replacement_dispatched', 'Replacement Dispatched')], default='pending', max_length=30)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_method', models.CharField(default='wallet', max_length=30)),
                ('seller_remarks', models.TextField(blank=True, default='')),
                ('admin_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
