# Generated by Django 6.1.1 on 2026-09-27 15:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverypartnerprofile_registration_details'),
        ('orders', '0003_order_delivered_at_order_replacement_for'),
        ('returns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickups', to='delivery.deliverypartnerprofile'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_tracking_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='replacement_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_return_request', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Seller Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_failed', 'Pickup Failed'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_picked_up', 'Item Picked Up'), ('inspection_passed', 'Inspection Passed'), ('inspection_failed', 'Inspection Failed'), ('refund_pending', 'Refund Pending'), ('refund_processed', 'Refund Completed'), ('refund_failed', 'Refund Failed'), ('replacement_pending', 'Replacement Pending'), ('replacement_reserved', 'Replacement Reserved'), ('replacement_dispatched', 'Replacement Dispatched'), ('replacement_delivered', 'Replacement Delivered'), ('replacement_failed', 'Replacement Failed')], default='pending', max_length=30),
        ),
    ]
