# Generated by Django 6.1.1 on 2026-09-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnrequest_approved_at_returnrequest_inspected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='pickup_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Seller Review'), ('cancelled', 'Cancelled by Customer'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_failed', 'Pickup Failed'), ('pickup_scheduled', 'Pickup Scheduled'), ('item_picked_up', 'Item Picked Up'), ('inspection_passed', 'Inspection Passed'), ('inspection_failed', 'Inspection Failed'), ('refund_pending', 'Refund Pending'), ('refund_processed', 'Refund Completed'), ('refund_failed', 'Refund Failed'), ('replacement_pending', 'Replacement Pending'), ('replacement_reserved', 'Replacement Reserved'), ('replacement_dispatched', 'Replacement Dispatched'), ('replacement_delivered', 'Replacement Delivered'), ('replacement_failed', 'Replacement Failed')], default='pending', max_length=30),
        ),
    ]
