# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='settled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
