# Generated by Django 6.1.1 on 2026-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('photo_url_1', models.CharField(blank=True, default='', max_length=500)),
                ('photo_url_2', models.CharField(blank=True, default='', max_length=500)),
                ('photo_url_3', models.CharField(blank=True, default='', max_length=500)),
                ('seller_reply', models.TextField(blank=True, default='')),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
