# Generated by Django 6.1.1 on 2026-09-27 18:10

from django.db import migrations, models


def seed_faq_items(apps, schema_editor):
    FAQItem = apps.get_model('admin_panel', 'FAQItem')
    FAQItem.objects.bulk_create([
        FAQItem(question='How can I place an order?', answer='Browse products, add your desired products to cart and complete the checkout process.', ordering=1),
        FAQItem(question='How can I track my order?', answer='You can track your order from your Orders section.', ordering=2),
        FAQItem(question='What payment methods are supported?', answer='Available payment methods will be displayed during checkout.', ordering=3),
        FAQItem(question='Can I return a product?', answer='Products can be returned according to our return policy.', ordering=4),
        FAQItem(question='How can I become a seller?', answer='Visit the Become a Seller page and submit your registration details.', ordering=5),
        FAQItem(question='How can I become a delivery partner?', answer='Visit the Delivery Partner registration page and submit your details.', ordering=6),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordering', 'id'),
            },
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='cancellation_policy',
            field=models.TextField(default='Customers may cancel an order when cancellation is available for that order.\n\nOrders that have already been shipped may not be eligible for cancellation and may need to follow the return process.\n\nEligible cancelled orders will be handled according to the applicable refund policy.'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='hero_badge',
            field=models.CharField(default='Mega Electronics & Lifestyle Sale', max_length=120),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='hero_subtitle',
            field=models.TextField(default="India's premier e-commerce marketplace with verified stores, secure doorstep delivery, and instant wallet refunds."),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='hero_title',
            field=models.CharField(default='Smart Shopping. Express OTP Delivery.', max_length=200),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='privacy_policy',
            field=models.TextField(default='We may collect information required to create accounts, process orders and provide services.\n\nInformation may be used to process orders, provide customer support and improve our services.\n\nWe take reasonable measures to protect user information.'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='refund_policy',
            field=models.TextField(default='Refund eligibility depends on the product, order status and applicable return conditions.\n\nOnce an eligible return is approved, the refund will be processed according to the applicable payment method.'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='shipping_policy',
            field=models.TextField(default='Orders are shipped to the address provided during checkout.\n\nDelivery time may vary depending on location, product availability and shipping conditions.\n\nWhere available, customers can track their order from the order details page.'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='terms_conditions',
            field=models.TextField(default='Users must use the platform lawfully and responsibly.\n\nUsers are responsible for maintaining the security of their account credentials.\n\nOrders are subject to product availability, pricing and applicable policies.'),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='marketplacesettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(seed_faq_items, migrations.RunPython.noop),
    ]
