# Generated by Django 6.1.1 on 2026-09-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_marketplacesettings_featured_product_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/slides/')),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('ordering', 'id'),
            },
        ),
    ]
